version: "3"
services:
  #Genarators Services
  genaretors-csv-services:
    container_name: csv-generator
    build:
      context: ./services/generators/csv
      dockerfile: service-build/Dockerfile
      args:
        - UID=${UID}
        - IMAGE_VERSION=${GEN_CSV_IMAGE_VERSION}
    volumes:
    - ./services/generators/csv/src:/var/www/html
    ports:
    - ${GEN_CSV_PORT}:8000
